apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: wordpress-app-set
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: dev
            namespace: wordpress-dev
            valuesFile: values-dev.yaml
          - name: staging
            namespace: wordpress-staging
            valuesFile: values-staging.yaml
          - name: prod
            namespace: wordpress-prod
            valuesFile: values-prod.yaml
  template:
    metadata:
      name: wordpress-{{name}}
    spec:
      project: default
      source:
        repoURL: https://github.com/your-repo/argocd-config.git
        path: helm/wordpress
        targetRevision: HEAD
        helm:
          valueFiles:
            - "{{valuesFile}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
