apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-repo/argocd-config.git
    path: helm/wordpress
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
