apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ahmad0303/HelmChart-with-ArgoCD-Deploying_Wordpress.git
    path: wordpress
    targetRevision: main
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true