apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets-prod
type: Opaque
data:
  mysql-root-password: cHJvZHJvb3RwYXNz        # base64 encoded "prodrootpass"
  mysql-database: bXlkYXRhYmFzZS1wcm9k             # base64 encoded "mydatabase-prod"
  mysql-username: cHJvZHVzZXI=                 # base64 encoded "produser"
  mysql-password: cHJvZHBhc3N3b3Jk             # base64 encoded "prodpassword"

---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secrets-prod
type: Opaque
data:
  wordpress-db-password: cHJvZHBhc3N3b3Jk      # base64 encoded "prodpassword"