apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets-dev
type: Opaque
data:
  mysql-root-password: bXlkZXZwYXNzd29yZA==  # base64 encoded "mydevpassword"
  mysql-database: bXlkYXRhYmFzZS1kZXY=       # base64 encoded "mydatabase-dev"
  mysql-username: bXlkZXZ1c2Vy               # base64 encoded "mydevuser"
  mysql-password: bXlkZXZ1c2VycGFzc3dvcmQ=   # base64 encoded "mydevuserpassword"

---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secrets-dev
type: Opaque
data:
  wordpress-db-password: bXlkZXZ1c2VycGFzc3dvcmQ=  # base64 encoded "mydevuserpassword"
