apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets-staging
type: Opaque
data:
  mysql-root-password: c3RhZ2luZ3Jvb3RwYXNz  # base64 encoded "stagingrootpass"
  mysql-database: bXlkYXRhYmFzZS1zdGFnaW5n       # base64 encoded "mydatabase-staging"
  mysql-username: c3RhZ2luZ3VzZXI=           # base64 encoded "staginguser"
  mysql-password: c3RhZ2luZ3Bhc3N3b3Jk       # base64 encoded "stagingpassword"

---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secrets-staging
type: Opaque
data:
  wordpress-db-password: c3RhZ2luZ3Bhc3N3b3Jk  # base64 encoded "stagingpassword"