environment: dev

image:
  repository: mysql
  tag: 5.7
  pullPolicy: IfNotPresent

auth:
  secretName: mysql-secrets-dev  

persistence:
  enabled: true
  size: 8Gi

service:
  type: LoadBalancer
  port: 3306

wordpress:
  enabled: true
  image:
    repository: wordpress
    tag: latest
  service:
    type: LoadBalancer
    port: 80
  env:
    secretName: wordpress-secrets-dev
    dbHost: wordpress-dev 
    dbName: mydatabase-dev