apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "wordpress.fullname" . }}-pv
  labels:
    app: {{ include "wordpress.fullname" . }}
#   annotations:
#     "helm.sh/resource-policy": keep
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/{{ include "wordpress.fullname" . }}  # Change this for cloud storage
