apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress.fullname" . }}-wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ include "wordpress.fullname" . }}-wordpress
  template:
    metadata:
      labels:
        app: {{ include "wordpress.fullname" . }}-wordpress
    spec:
      containers:
        - name: wordpress
          image: {{ .Values.wordpress.image.repository }}:{{ .Values.wordpress.image.tag }}
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ .Values.wordpress.env.dbHost }}
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.secretName }}  
                  key: mysql-username
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.wordpress.env.secretName }}  
                  key: wordpress-db-password
            - name: WORDPRESS_DB_NAME
              value: {{ .Values.wordpress.env.dbName }}
          ports:
            - containerPort: 80